=== ederico23/1DAW-MARCAS/XML/practica2/jugadores.dtd
<!-- Definición del DTD para la lista de jugadores -->
<!ELEMENT jugadores (jugador+)>

<!-- Definición de elementos -->
<!ELEMENT jugador (nombre, apellido, edad, valorMercado, juegaSeleccion)>

<!-- Definición de atributos -->
<!ATTLIST jugador id ID #REQUIRED>

<!-- Definición de datos s-->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT valorMercado (#PCDATA)>
<!ELEMENT juegaSeleccion (#PCDATA)>

=== ederico23/1DAW-MARCAS/XML/practica1/03-ejercicio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jugadores SYSTEM "jugadores.dtd">

<jugadores>

    <jugador id = "j1">
        <nombre> </nombre>
        <apellido> </apellido>
        <edad> </edad> 
        <valorMercado> </valorMercado>
        <juegaSeleccion> </juegaSeleccion>
    </jugador>

    <jugador id = "j2">
        <nombre> </nombre>
        <apellido> </apellido>
        <edad> </edad> 
        <valorMercado> </valorMercado>
        <juegaSeleccion> </juegaSeleccion>
    </jugador>

    <jugador id = "j3">
        <nombre> </nombre>
        <apellido> </apellido>
        <edad> </edad> 
        <valorMercado> </valorMercado>
        <juegaSeleccion> </juegaSeleccion>
    </jugador>

</jugadores>
