=== ederico23/1DAW-MARCAS/XML/practica2/vehiculos.dtd
<!ELEMENT vehiculos (coches|motos)*>

<!ELEMENT coches (coche)>
<!ELEMENT coche (planta_aparcamiento, marca, modelo, color, minusválido, matriculacion, imagen, propietario)>

<!ATTLIST coche
          matricula CDATA #REQUIRED>
<!ELEMENT planta_aparcamiento (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT minusválido (#PCDATA)>
<!ELEMENT matriculacion (#PCDATA)>

<!ELEMENT imagen EMPTY>
<!ATTLIST imagen
          extension CDATA #REQUIRED
          nombre CDATA #REQUIRED>

<!ELEMENT propietario (nombre, apellidos, telefono)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre
          dni CDATA #REQUIRED>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

<!ELEMENT motos (moto)>
<!ELEMENT moto (planta_aparcamiento, marca, modelo, color, minusválido, matriculacion, imagen, propietario)>

<!ATTLIST moto
          matricula CDATA #REQUIRED>

=== ederico23/1DAW-MARCAS/XML/practica2/vehiculos.xml
<?xml version = "1.0" encoding="UTF-8"?>
<!DOCTYPE vehiculos SYSTEM "vehiculos.dtd">

<vehiculos>

    <coches>

        <coche matricula=" ">
            <planta_aparcamiento> </planta_aparcamiento>
            <marca> </marca>
            <modelo> </modelo>
            <color> </color>
            <minusválido> </minusválido>   
            <matriculacion> </matriculacion>
            <imagen extension="" nombre="" />
            <propietario> 
                <nombre dni=" "></nombre>
                <apellidos> </apellidos>
                <telefono> </telefono>
            </propietario>
        </coche>

    </coches>

    <motos>

        <moto matricula=" ">
            <planta_aparcamiento> </planta_aparcamiento>
            <marca> </marca>
            <modelo> </modelo>
            <color> </color>
            <minusválido> </minusválido>   
            <matriculacion> </matriculacion>
            <imagen extension="" nombre=""/>
            <propietario> 
                <nombre dni=" "></nombre>
                <apellidos> </apellidos>
                <telefono> </telefono>
            </propietario>
        </moto>
    
    </motos>
</vehiculos>
