=== ederico23/1DAW-MARCAS/XML/practica3/excursion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="tipoIdAlumno">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{8}[A-Z]|[XYZ][0-9]{7}[A-Z]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoGrupo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DAW1D"/>
      <xs:enumeration value="DAM1D"/>
      <xs:enumeration value="ASIR1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="excursion">
    <xs:complexType>
      <xs:sequence>
        
        <xs:element name="profesor" minOccurs="1" maxOccurs="5">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="NRP" type="xs:string"/>
              <xs:element name="telefono" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="alumno" minOccurs="10" maxOccurs="100">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="telefono_padres" type="xs:string"/>
              <xs:element name="fecha_nacimiento" type="xs:date"/>
              <xs:element name="edad" type="xs:integer"/>
            </xs:sequence>
            <xs:attribute name="id_alumno" type="tipoIdAlumno" use="required"/>
            <xs:attribute name="grupo" type="tipoGrupo" default="DAW1D"/>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== ederico23/1DAW-MARCAS/XML/practica3/excursion.xml
<?xml version="1.0" encoding="UTF-8"?>
<excursion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="excursion.xsd">

    <profesor>
        <nombre>Javier Rodríguez</nombre>
        <NRP>1234567890A2025</NRP>
        <telefono>600111222</telefono>
    </profesor>

    <alumno id_alumno="12345678Z" grupo="DAW1D">
        <nombre>Carla Pérez</nombre>
        <telefono_padres>699888777</telefono_padres>
        <fecha_nacimiento>2005-05-15</fecha_nacimiento>
        <edad>20</edad>
    </alumno>

    </excursion>
